name: Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:alpine
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install --global pnpm

      - name: Install packages
        run: |
          rm -f pnpm-lock.yaml
          pnpm update

      - name: Build
        env:
          VITE_BASE_PUBLIC_PATH: ${{ secrets.VITE_BASE_PUBLIC_PATH }}
        run: pnpm run build

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy to oss
        uses: yizhoumo/setup-ossutil@v1
        with:
          endpoint: ${{ secrets.OSS_GDCN_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_GDCN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_GDCN_ACCESS_KEY_SECRET }}
        run: |
          ossutil rm -r oss://gdcn/static/gdpw
          ossutil cp -r ./dist oss://gdcn/static/gdpw